import httpx
from fastapi import HTTPException
from app.core.config import settings

ELEVENLABS_API_URL = "https://api.elevenlabs.io/v1"

class ElevenLabsClient:
    def __init__(self):
        self.api_key = settings.ELEVENLABS_API_KEY
        self.headers = {
            "xi-api-key": self.api_key,
            "Content-Type": "application/json"
        }

    def is_configured(self):
        return self.api_key is not None

    def generate_speech(self, text: str, voice_id: str) -> bytes:
        """
        Generates speech using the ElevenLabs API and returns the audio bytes.
        """
        if not self.is_configured():
            raise ValueError("ElevenLabs API Key is not configured.")

        url = f"{ELEVENLABS_API_URL}/text-to-speech/{voice_id}"
        
        payload = {
            "text": text,
            "model_id": "eleven_monolingual_v1",
            "voice_settings": {
                "stability": 0.5,
                "similarity_boost": 0.75
            }
        }

        with httpx.Client() as client:
            response = client.post(url, json=payload, headers=self.headers, timeout=60.0)
            
            if response.status_code != 200:
                raise Exception(f"ElevenLabs API Error: {response.status_code} - {response.text}")
                
            return response.content

    def get_voices(self) -> list[dict]:
        """
        Retrieves all voices available to the user.
        """
        if not self.is_configured():
            return []

        url = f"{ELEVENLABS_API_URL}/voices"
        
        with httpx.Client() as client:
            response = client.get(url, headers=self.headers)
            if response.status_code == 200:
                return response.json().get("voices", [])
            return []

    def add_voice(self, name: str, description: str, file_paths: list[str]) -> str:
        """
        Uploads audio samples to ElevenLabs to create a new cloned voice.
        Returns the external_voice_id generated by ElevenLabs.
        """
        if not self.is_configured():
            raise ValueError("ElevenLabs API Key is not configured.")

        url = f"{ELEVENLABS_API_URL}/voices/add"
        
        # ElevenLabs requires multipart/form-data for this endpoint
        headers = {
            "xi-api-key": self.api_key
            # Do NOT set Content-Type here, httpx will set it correctly with boundaries
        }
        
        data = {
            "name": name,
            "description": description or ""
        }
        
        files = []
        for path in file_paths:
            # files is a list of tuples: ("files", (filename, file_object, content_type))
            files.append(("files", (path.split('/')[-1], open(path, "rb"), "audio/mpeg")))
            
        try:
            with httpx.Client() as client:
                response = client.post(url, headers=headers, data=data, files=files, timeout=120.0)
                
                if response.status_code != 200:
                    raise Exception(f"ElevenLabs API Error: {response.status_code} - {response.text}")
                    
                return response.json().get("voice_id")
        finally:
            # Ensure all file objects are closed
            for _, (_, f_obj, _) in files:
                f_obj.close()

tts_engine = ElevenLabsClient()
