"""add external_voice_id

Revision ID: 23f1b063d336
Revises: 63ce9f06fd51
Create Date: 2026-08-18 00:54:41.550611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f1b063d336'
down_revision: Union[str, None] = '63ce9f06fd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_profiles', sa.Column('external_voice_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_profiles', 'external_voice_id')
    # ### end Alembic commands ###
