"""add_chars_generated_this_month_to_usage_stats

Revision ID: 6333add60711
Revises: 23f1b063d336
Create Date: 2026-08-18 21:46:44.645927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6333add60711'
down_revision: Union[str, None] = '23f1b063d336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_usage_stats', sa.Column('chars_generated_this_month', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_usage_stats', 'chars_generated_this_month')
    # ### end Alembic commands ###
