"""001_initial_schema

Revision ID: 63ce9f06fd51
Revises: 
Create Date: 2026-08-16 19:55:35.806430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ce9f06fd51'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('auth_provider', sa.Enum('email', 'google', name='auth_provider'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('user_usage_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_generations', sa.Integer(), nullable=False),
    sa.Column('total_voice_profiles', sa.Integer(), nullable=False),
    sa.Column('total_audio_uploads', sa.Integer(), nullable=False),
    sa.Column('total_output_seconds', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('generations_this_month', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), server_default=sa.text("date_trunc('month', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('voice_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('embedding_r2_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', 'archived', name='voice_profile_status'), nullable=False),
    sa.Column('processing_error', sa.String(), nullable=True),
    sa.Column('sample_count', sa.SmallInteger(), nullable=False),
    sa.Column('total_duration_sec', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voice_profiles_status', 'voice_profiles', ['status'], unique=False)
    op.create_index('idx_voice_profiles_user_id', 'voice_profiles', ['user_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_voice_profiles_user_status', 'voice_profiles', ['user_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('generation_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('voice_profile_id', sa.UUID(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='generation_status'), nullable=False),
    sa.Column('input_text', sa.String(), nullable=False),
    sa.Column('input_text_length', sa.Integer(), sa.Computed('char_length(input_text)', persisted=True), nullable=True),
    sa.Column('output_r2_path', sa.String(), nullable=True),
    sa.Column('output_duration_sec', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(input_text) BETWEEN 1 AND 5000', name='chk_input_text_length'),
    sa.CheckConstraint('retry_count >= 0 AND retry_count <= 5', name='chk_retry_count'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index('idx_gen_history_celery_task', 'generation_history', ['celery_task_id'], unique=False)
    op.create_index('idx_gen_history_status', 'generation_history', ['status'], unique=False, postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.create_index('idx_gen_history_user_id', 'generation_history', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_gen_history_user_status', 'generation_history', ['user_id', 'status'], unique=False)
    op.create_index('idx_gen_history_voice_profile', 'generation_history', ['voice_profile_id'], unique=False)
    op.create_table('voice_audio_samples',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('voice_profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('r2_object_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('duration_sec', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=True),
    sa.Column('channels', sa.SmallInteger(), nullable=True),
    sa.Column('is_preprocessed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mime_type IN ('audio/wav', 'audio/mpeg', 'audio/x-wav')", name='chk_mime_type'),
    sa.CheckConstraint('file_size_bytes > 0 AND file_size_bytes <= 52428800', name='chk_file_size'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_profile_id'], ['voice_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('r2_object_key')
    )
    op.create_index('idx_voice_samples_profile_id', 'voice_audio_samples', ['voice_profile_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_voice_samples_user_id', 'voice_audio_samples', ['user_id'], unique=False)
    
    # Custom Trigger for updated_at
    op.execute("""
    CREATE OR REPLACE FUNCTION trigger_set_updated_at()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = NOW();
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER set_updated_at_users
        BEFORE UPDATE ON users
        FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
    """)
    
    op.execute("""
    CREATE TRIGGER set_updated_at_voice_profiles
        BEFORE UPDATE ON voice_profiles
        FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
    """)

    op.execute("""
    CREATE TRIGGER set_updated_at_generation_history
        BEFORE UPDATE ON generation_history
        FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
    """)

    op.execute("""
    CREATE TRIGGER set_updated_at_usage_stats
        BEFORE UPDATE ON user_usage_stats
        FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop Custom Triggers
    op.execute("DROP TRIGGER IF EXISTS set_updated_at_usage_stats ON user_usage_stats;")
    op.execute("DROP TRIGGER IF EXISTS set_updated_at_generation_history ON generation_history;")
    op.execute("DROP TRIGGER IF EXISTS set_updated_at_voice_profiles ON voice_profiles;")
    op.execute("DROP TRIGGER IF EXISTS set_updated_at_users ON users;")
    op.execute("DROP FUNCTION IF EXISTS trigger_set_updated_at();")

    op.drop_index('idx_voice_samples_user_id', table_name='voice_audio_samples')
    op.drop_index('idx_voice_samples_profile_id', table_name='voice_audio_samples', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('voice_audio_samples')
    op.drop_index('idx_gen_history_voice_profile', table_name='generation_history')
    op.drop_index('idx_gen_history_user_status', table_name='generation_history')
    op.drop_index('idx_gen_history_user_id', table_name='generation_history')
    op.drop_index('idx_gen_history_status', table_name='generation_history', postgresql_where=sa.text("status IN ('queued', 'processing')"))
    op.drop_index('idx_gen_history_celery_task', table_name='generation_history')
    op.drop_table('generation_history')
    op.drop_index('idx_voice_profiles_user_status', table_name='voice_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_voice_profiles_user_id', table_name='voice_profiles', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_voice_profiles_status', table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_table('user_usage_stats')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_active', table_name='users', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
